/*
#ifndef AD_TRACKING_ERROR_H
#define AD_TRACKING_ERROR_H

#define ERROR_READ_PARAMS_TRACKING       0x05
#define ERROR_OPENING_FILE_DETECTOR      0x06
#define ERROR_WRITE_PARAM_DETECTOR       0x07
#define ERROR_READ_PARAM_DETECTOR        0x08

#endif // AD_TRACKING_ERROR_H
*/
